# Generated by Django 3.0.8 on 2020-09-07 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('arm_1', models.TextField(blank=True, null=True)),
                ('arm_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteIdColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_of_options', models.IntegerField()),
                ('potential_values', models.TextField(blank=True, null=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_id_column', to='datastore.Table')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('randomization_arm', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_datetime', models.DateTimeField(blank=True, null=True)),
                ('reservation_datetime', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Table')),
            ],
            options={
                'ordering': ('patient_id', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_of_options', models.IntegerField()),
                ('potential_values', models.TextField(blank=True, null=True)),
                ('table_index', models.IntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Table')),
            ],
            options={
                'ordering': ('table_index',),
            },
        ),
        migrations.AddIndex(
            model_name='row',
            index=models.Index(fields=['key'], name='datastore_r_key_8a908a_idx'),
        ),
        migrations.AddIndex(
            model_name='row',
            index=models.Index(fields=['table'], name='datastore_r_table_i_c1fc50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('table', 'table_index'), ('table', 'name')},
        ),
    ]
