# Generated by Django 3.0.8 on 2020-09-07 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import permissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSiteIdAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TablePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('table', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=permissions.models.ActivationCode.generate_code, max_length=16, unique=True, validators=[permissions.models.ActivationCode.activation_code_validator])),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Table')),
            ],
            options={
                'unique_together': {('table', 'site_id')},
            },
        ),
    ]
